name: Build/release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Electron app
        run: |
          yarn install
          yarn build

      - name: Upload [Motrix Setup] artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Motrix-Setup
          path: release/Motrix-Setup-*.*.*.exe

      - name: Upload [Motrix] artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Motrix
          path: release/Motrix-*.*.*.exe

      - name: Upload [Motrix x864] artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Motrix-x64
          path: release/Motrix-*.*.*-x64.exe

      - name: Upload [Motrix ia32] artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Motrix-ia32
          path: release/Motrix-*.*.*-ia32.exe

      - name: Upload [Motrix ia32 Zip] artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Motrix-ia32-zip
          path: release/Motrix-*.*.*-ia32-win.zip

      - name: Upload [Motrix x64 Zip] artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Motrix-x64-zip
          path: release/Motrix-*.*.*-win.zip
