name: Build/release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Electron app
        run: |
          yarn install
          yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-files
          path: |
            release/*.zip
            release/*.exe
